[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.10.15"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.5.0"

[[constraint]]
  branch = "master"
  name = "github.com/goware/prefixer"

[[constraint]]
  branch = "master"
  name = "github.com/jawher/mow.cli"

[[constraint]]
  name = "github.com/mattn/go-shellwords"
  version = "1.0.3"

[[constraint]]
  branch = "master"
  name = "github.com/olekukonko/tablewriter"

[[constraint]]
  branch = "master"
  name = "github.com/vaughan0/go-ini"
